import { DISPLAY_MODES } from "../../visualizationSchema.js";
import { registerThreeMode } from "./threeModeRegistry.js";
import { createPlasmaFieldRenderer } from "./plasmaFieldRenderer.js";
import { createParticleGalaxyRenderer } from "./particleGalaxyRenderer.js";
import { createBloomTunnelRenderer } from "./bloomTunnelRenderer.js";
import { createEnergySphereRenderer } from "./energySphereRenderer.js";
import { createKaleidoscopeRenderer } from "./kaleidoscopeRenderer.js";
import { createGlitchSpectrumRenderer } from "./glitchSpectrumRenderer.js";
import { createPhosphorTrailRenderer } from "./phosphorTrailRenderer.js";
import { createScanGridRenderer } from "./scanGridRenderer.js";
import { createLiquidBlobRenderer } from "./liquidBlobRenderer.js";
import { createAuroraRibbonRenderer } from "./auroraRibbonRenderer.js";
import { createBreathingRingsRenderer } from "./breathingRingsRenderer.js";
import { createNoiseLandscapeRenderer } from "./noiseLandscapeRenderer.js";
import { createLavaLampRenderer } from "./lavaLampRenderer.js";
import { createOilMarbleRenderer } from "./oilMarbleRenderer.js";
import { createPearlChainRenderer } from "./pearlChainRenderer.js";
import { createCrystalGemRenderer } from "./crystalGemRenderer.js";
import { createGlassOrbsRenderer } from "./glassOrbsRenderer.js";
import { createHoloPrismRenderer } from "./holoPrismRenderer.js";
import { createNebulaVolumeRenderer } from "./nebulaVolumeRenderer.js";
import { createKnotOrganicRenderer } from "./knotOrganicRenderer.js";
import { createCoverParticleRenderer } from "./coverParticle/coverParticleRenderer.js";
import { createSoundFieldRenderer } from "./soundField/soundFieldRenderer.js";

registerThreeMode(DISPLAY_MODES.threeCoverParticle, createCoverParticleRenderer);
registerThreeMode(DISPLAY_MODES.threeSoundField, createSoundFieldRenderer);
registerThreeMode(DISPLAY_MODES.threePlasmaField, createPlasmaFieldRenderer);
registerThreeMode(DISPLAY_MODES.threeParticleGalaxy, createParticleGalaxyRenderer);
registerThreeMode(DISPLAY_MODES.threeBloomTunnel, createBloomTunnelRenderer);
registerThreeMode(DISPLAY_MODES.threeEnergySphere, createEnergySphereRenderer);
registerThreeMode(DISPLAY_MODES.threeKaleidoscope, createKaleidoscopeRenderer);
registerThreeMode(DISPLAY_MODES.threeGlitchSpectrum, createGlitchSpectrumRenderer);
registerThreeMode(DISPLAY_MODES.threePhosphorTrail, createPhosphorTrailRenderer);
registerThreeMode(DISPLAY_MODES.threeScanGrid, createScanGridRenderer);
registerThreeMode(DISPLAY_MODES.threeLiquidBlob, createLiquidBlobRenderer);
registerThreeMode(DISPLAY_MODES.threeAuroraRibbon, createAuroraRibbonRenderer);
registerThreeMode(DISPLAY_MODES.threeBreathingRings, createBreathingRingsRenderer);
registerThreeMode(DISPLAY_MODES.threeNoiseLandscape, createNoiseLandscapeRenderer);
registerThreeMode(DISPLAY_MODES.threeLavaLamp, createLavaLampRenderer);
registerThreeMode(DISPLAY_MODES.threeOilMarble, createOilMarbleRenderer);
registerThreeMode(DISPLAY_MODES.threePearlChain, createPearlChainRenderer);
registerThreeMode(DISPLAY_MODES.threeCrystalGem, createCrystalGemRenderer);
registerThreeMode(DISPLAY_MODES.threeGlassOrbs, createGlassOrbsRenderer);
registerThreeMode(DISPLAY_MODES.threeHoloPrism, createHoloPrismRenderer);
registerThreeMode(DISPLAY_MODES.threeNebulaVolume, createNebulaVolumeRenderer);
registerThreeMode(DISPLAY_MODES.threeKnotOrganic, createKnotOrganicRenderer);
