import { DISPLAY_MODES } from "../../visualizationSchema.js";
import { registerThreeMode } from "./threeModeRegistry.js";
import { createPlasmaFieldRenderer } from "./plasmaFieldRenderer.js";
import { createParticleGalaxyRenderer } from "./particleGalaxyRenderer.js";
import { createBloomTunnelRenderer } from "./bloomTunnelRenderer.js";
import { createEnergySphereRenderer } from "./energySphereRenderer.js";
import { createKaleidoscopeRenderer } from "./kaleidoscopeRenderer.js";
import { createGlitchSpectrumRenderer } from "./glitchSpectrumRenderer.js";
import { createPhosphorTrailRenderer } from "./phosphorTrailRenderer.js";
import { createScanGridRenderer } from "./scanGridRenderer.js";
import { createLiquidBlobRenderer } from "./liquidBlobRenderer.js";
import { createAuroraRibbonRenderer } from "./auroraRibbonRenderer.js";
import { createBreathingRingsRenderer } from "./breathingRingsRenderer.js";

registerThreeMode(DISPLAY_MODES.threePlasmaField, createPlasmaFieldRenderer);
registerThreeMode(DISPLAY_MODES.threeParticleGalaxy, createParticleGalaxyRenderer);
registerThreeMode(DISPLAY_MODES.threeBloomTunnel, createBloomTunnelRenderer);
registerThreeMode(DISPLAY_MODES.threeEnergySphere, createEnergySphereRenderer);
registerThreeMode(DISPLAY_MODES.threeKaleidoscope, createKaleidoscopeRenderer);
registerThreeMode(DISPLAY_MODES.threeGlitchSpectrum, createGlitchSpectrumRenderer);
registerThreeMode(DISPLAY_MODES.threePhosphorTrail, createPhosphorTrailRenderer);
registerThreeMode(DISPLAY_MODES.threeScanGrid, createScanGridRenderer);
registerThreeMode(DISPLAY_MODES.threeLiquidBlob, createLiquidBlobRenderer);
registerThreeMode(DISPLAY_MODES.threeAuroraRibbon, createAuroraRibbonRenderer);
registerThreeMode(DISPLAY_MODES.threeBreathingRings, createBreathingRingsRenderer);
