export const STORAGE_KEYS = {
  lineShape: "wavedance.waveShapeConfig",
  barShape: "wavedance.barShapeConfig",
  displayMode: "wavedance.displayMode",
  panelStyleMode: "wavedance.panelStyleMode",
  freqReversed: "wavedance.freqReversed",
  lineColor: "wavedance.lineColor",
  lineWidth: "wavedance.lineWidthPx",
  barColor: "wavedance.barColor",
  barWidth: "wavedance.barWidthPercent",
  barGap: "wavedance.barGapPercent",
  barHeadroom: "wavedance.barHeadroomPercent",
  barOrientation: "wavedance.barOrientation",
  barMirror: "wavedance.barMirrorEnabled",
  barPeakHold: "wavedance.barPeakHoldEnabled",
  barPeakHoldMode: "wavedance.barPeakHoldMode",
  barPeakColor: "wavedance.barPeakColor",
  barPeakFallSpeed: "wavedance.barPeakFallSpeed",
  barPeakThickness: "wavedance.barPeakThickness",
  areaColor: "wavedance.areaFillColor",
  areaLineColor: "wavedance.areaLineColor",
  areaFillAlpha: "wavedance.areaFillAlphaPercent",
  areaLineWidth: "wavedance.areaLineWidthPx",
  areaMirror: "wavedance.areaMirrorEnabled",
  areaGradient: "wavedance.areaGradientEnabled",
  areaShape: "wavedance.areaShapeConfig",
  gradientBarColorLow: "wavedance.gradientBarColorLow",
  gradientBarColorHigh: "wavedance.gradientBarColorHigh",
  gradientBarWidth: "wavedance.gradientBarWidthPercent",
  gradientBarGap: "wavedance.gradientBarGapPercent",
  gradientBarHeadroom: "wavedance.gradientBarHeadroomPercent",
  gradientBarOrientation: "wavedance.gradientBarOrientation",
  gradientBarMirror: "wavedance.gradientBarMirrorEnabled",
  gradientBarPeakHoldMode: "wavedance.gradientBarPeakHoldMode",
  gradientBarPeakColor: "wavedance.gradientBarPeakColor",
  gradientBarPeakFallSpeed: "wavedance.gradientBarPeakFallSpeed",
  gradientBarPeakThickness: "wavedance.gradientBarPeakThickness",
  gradientBarShape: "wavedance.gradientBarShapeConfig",
  glowLineCoreColor: "wavedance.glowLineCoreColor",
  glowLineGlowColor: "wavedance.glowLineGlowColor",
  glowLineWidth: "wavedance.glowLineWidthPx",
  glowLineGlowRadius: "wavedance.glowLineGlowRadiusPx",
  glowLineGlowIntensity: "wavedance.glowLineGlowIntensityPercent",
  glowLineShape: "wavedance.glowLineShapeConfig",
  glowCircleCoreColor: "wavedance.glowCircleCoreColor",
  glowCircleGlowColor: "wavedance.glowCircleGlowColor",
  glowCircleWidth: "wavedance.glowCircleWidthPx",
  glowCircleGlowRadius: "wavedance.glowCircleGlowRadiusPx",
  glowCircleGlowIntensity: "wavedance.glowCircleGlowIntensityPercent",
  glowCircleShape: "wavedance.glowCircleShapeConfig",
  glowCircleRingRadius: "wavedance.glowCircleRingRadiusPercent",
  glowCircleRotation: "wavedance.glowCircleRotationOffsetDeg",
  glowCircleClockwise: "wavedance.glowCircleClockwise",
  radialColor: "wavedance.radialBarColor",
  radialInnerRadius: "wavedance.radialInnerRadiusPercent",
  radialOuterRadius: "wavedance.radialOuterRadiusPercent",
  radialBarThickness: "wavedance.radialBarThicknessPercent",
  radialMirror: "wavedance.radialMirrorEnabled",
  radialRotation: "wavedance.radialRotationOffsetDeg",
  radialClockwise: "wavedance.radialClockwise",
  radialShape: "wavedance.radialShapeConfig",
  waterfallColorLow: "wavedance.waterfallColorLow",
  waterfallColorHigh: "wavedance.waterfallColorHigh",
  waterfallHistoryRows: "wavedance.waterfallHistoryRows",
  waterfallScrollEveryNFrames: "wavedance.waterfallScrollEveryNFrames",
  waterfallRowGap: "wavedance.waterfallRowGapPercent",
  waterfallShape: "wavedance.waterfallShapeConfig",
  dotRingColor: "wavedance.dotRingDotColor",
  dotRingRadius: "wavedance.dotRingRadiusPercent",
  dotRingCount: "wavedance.dotRingDotCount",
  dotRingSize: "wavedance.dotRingDotSizePx",
  dotRingPulse: "wavedance.dotRingPulseEnabled",
  dotRingShape: "wavedance.dotRingShapeConfig",
  oscilloscopeColor: "wavedance.oscilloscopeLineColor",
  oscilloscopeLineWidth: "wavedance.oscilloscopeLineWidthPx",
  oscilloscopePhosphor: "wavedance.oscilloscopePhosphorEnabled",
  oscilloscopePhosphorDecay: "wavedance.oscilloscopePhosphorDecayPercent",
  obliqueBarColor: "wavedance.obliqueBarColor",
  obliqueBarColorFar: "wavedance.obliqueBarColorFar",
  obliqueBarWidth: "wavedance.obliqueBarWidthPercent",
  obliqueBarGap: "wavedance.obliqueBarGapPercent",
  obliqueBarHeadroom: "wavedance.obliqueBarHeadroomPercent",
  obliqueBarTilt: "wavedance.obliqueBarTiltDeg",
  obliqueBarGroundLine: "wavedance.obliqueBarShowGroundLine",
  obliqueBarMirror: "wavedance.obliqueBarMirrorEnabled",
  obliqueBarDisplayCount: "wavedance.obliqueBarDisplayBarCount",
  obliqueBarShape: "wavedance.obliqueBarShapeConfig",
  depthLayersCount: "wavedance.depthLayersLayerCount",
  depthLayersSpacing: "wavedance.depthLayersLayerSpacingPx",
  depthLayersFarScale: "wavedance.depthLayersFarScalePercent",
  depthLayersFarAlpha: "wavedance.depthLayersFarAlphaPercent",
  depthLayersBassFront: "wavedance.depthLayersBassFrontEnabled",
  depthLayersColor: "wavedance.depthLayersColor",
  depthLayersColorFar: "wavedance.depthLayersColorFar",
  depthLayersLineWidth: "wavedance.depthLayersLineWidthPx",
  depthLayersRenderStyle: "wavedance.depthLayersRenderStyle",
  depthLayersShape: "wavedance.depthLayersShapeConfig",
  isometricSkylineFaceTop: "wavedance.isometricSkylineFaceTopColor",
  isometricSkylineFaceLeft: "wavedance.isometricSkylineFaceLeftColor",
  isometricSkylineFaceRight: "wavedance.isometricSkylineFaceRightColor",
  isometricSkylineBuildingWidth: "wavedance.isometricSkylineBuildingWidthPx",
  isometricSkylineBuildingGap: "wavedance.isometricSkylineBuildingGapPx",
  isometricSkylineBaseline: "wavedance.isometricSkylineBaselinePercent",
  isometricSkylineBuildingCount: "wavedance.isometricSkylineDisplayBuildingCount",
  isometricSkylineGroundPlane: "wavedance.isometricSkylineShowGroundPlane",
  isometricSkylineShape: "wavedance.isometricSkylineShapeConfig",
  ring3dColor: "wavedance.ring3dBarColor",
  ring3dInnerRadius: "wavedance.ring3dInnerRadius",
  ring3dOuterRadius: "wavedance.ring3dOuterRadius",
  ring3dBarHeightScale: "wavedance.ring3dBarHeightScale",
  ring3dBarThicknessDeg: "wavedance.ring3dBarThicknessDeg",
  ring3dDisplayCount: "wavedance.ring3dDisplayBarCount",
  ring3dWireframe: "wavedance.ring3dWireframeEnabled",
  ring3dFill: "wavedance.ring3dFillEnabled",
  ring3dAutoRotate: "wavedance.ring3dAutoRotateEnabled",
  ring3dAutoRotateSpeed: "wavedance.ring3dAutoRotateSpeedDeg",
  ring3dCameraDistance: "wavedance.ring3dCameraDistance",
  ring3dCameraFov: "wavedance.ring3dCameraFovDeg",
  ring3dBreathePeak: "wavedance.ring3dBreatheWithPeak",
  ring3dShape: "wavedance.ring3dShapeConfig",
  terrain3dColorLow: "wavedance.terrain3dColorLow",
  terrain3dColorHigh: "wavedance.terrain3dColorHigh",
  terrain3dWireframeColor: "wavedance.terrain3dWireframeColor",
  terrain3dGridCols: "wavedance.terrain3dGridCols",
  terrain3dGridRows: "wavedance.terrain3dGridRows",
  terrain3dScrollEveryNFrames: "wavedance.terrain3dScrollEveryNFrames",
  terrain3dWireframe: "wavedance.terrain3dWireframeEnabled",
  terrain3dFill: "wavedance.terrain3dFillEnabled",
  terrain3dHeightScale: "wavedance.terrain3dTerrainHeightScale",
  terrain3dCameraPitch: "wavedance.terrain3dCameraPitchDeg",
  terrain3dCameraDistance: "wavedance.terrain3dCameraDistance",
  terrain3dAutoScroll: "wavedance.terrain3dAutoScrollEnabled",
  terrain3dShape: "wavedance.terrain3dShapeConfig",
  helix3dColor: "wavedance.helix3dDotColor",
  helix3dRadius: "wavedance.helix3dHelixRadius",
  helix3dPitch: "wavedance.helix3dHelixPitch",
  helix3dTurns: "wavedance.helix3dHelixTurns",
  helix3dDisplayCount: "wavedance.helix3dDisplayPointCount",
  helix3dExtrudeMode: "wavedance.helix3dExtrudeMode",
  helix3dPointSize: "wavedance.helix3dPointSizePx",
  helix3dWireframe: "wavedance.helix3dWireframeEnabled",
  helix3dAutoRotate: "wavedance.helix3dAutoRotateEnabled",
  helix3dAutoRotateSpeed: "wavedance.helix3dAutoRotateSpeedDeg",
  helix3dCameraDistance: "wavedance.helix3dCameraDistance",
  helix3dCameraFov: "wavedance.helix3dCameraFovDeg",
  helix3dShape: "wavedance.helix3dShapeConfig",
  threePlasmaColorLow: "wavedance.threePlasmaColorLow",
  threePlasmaColorHigh: "wavedance.threePlasmaColorHigh",
  threePlasmaSpeed: "wavedance.threePlasmaSpeed",
  threePlasmaNoiseScale: "wavedance.threePlasmaNoiseScale",
  threePlasmaReactiveness: "wavedance.threePlasmaReactiveness",
  threePlasmaBloom: "wavedance.threePlasmaBloomEnabled",
  threePlasmaBloomStrength: "wavedance.threePlasmaBloomStrength",
  threePlasmaShape: "wavedance.threePlasmaShapeConfig",
  threeGalaxyColor: "wavedance.threeGalaxyParticleColor",
  threeGalaxyCount: "wavedance.threeGalaxyParticleCount",
  threeGalaxyRadius: "wavedance.threeGalaxyRadius",
  threeGalaxyArms: "wavedance.threeGalaxySpiralArms",
  threeGalaxyBassPull: "wavedance.threeGalaxyBassPullStrength",
  threeGalaxyTrebleSpread: "wavedance.threeGalaxyTrebleSpreadStrength",
  threeGalaxyBloom: "wavedance.threeGalaxyBloomEnabled",
  threeGalaxyBloomStrength: "wavedance.threeGalaxyBloomStrength",
  threeGalaxyAutoRotateSpeed: "wavedance.threeGalaxyAutoRotateSpeedDeg",
  threeGalaxyShape: "wavedance.threeGalaxyShapeConfig",
  threeTunnelWallColorLow: "wavedance.threeTunnelWallColorLow",
  threeTunnelWallColorHigh: "wavedance.threeTunnelWallColorHigh",
  threeTunnelCoreColor: "wavedance.threeTunnelCoreColor",
  threeTunnelSpeed: "wavedance.threeTunnelSpeed",
  threeTunnelWallSegments: "wavedance.threeTunnelWallSegments",
  threeTunnelCorePulseStrength: "wavedance.threeTunnelCorePulseStrength",
  threeTunnelBloom: "wavedance.threeTunnelBloomEnabled",
  threeTunnelBloomStrength: "wavedance.threeTunnelBloomStrength",
  threeTunnelFov: "wavedance.threeTunnelFovDeg",
  threeTunnelShape: "wavedance.threeTunnelShapeConfig",
  threeSphereCoreColor: "wavedance.threeSphereCoreColor",
  threeSphereHaloColor: "wavedance.threeSphereHaloColor",
  threeSphereDeformStrength: "wavedance.threeSphereDeformStrength",
  threeSphereNoiseSpeed: "wavedance.threeSphereNoiseSpeed",
  threeSphereHaloCount: "wavedance.threeSphereHaloParticleCount",
  threeSphereWireframe: "wavedance.threeSphereWireframeOverlay",
  threeSphereBloom: "wavedance.threeSphereBloomEnabled",
  threeSphereBloomStrength: "wavedance.threeSphereBloomStrength",
  threeSphereAutoRotateSpeed: "wavedance.threeSphereAutoRotateSpeedDeg",
  threeSphereShape: "wavedance.threeSphereShapeConfig",
  threeKaleidoscopeSegments: "wavedance.threeKaleidoscopeSegments",
  threeKaleidoscopeColorLow: "wavedance.threeKaleidoscopeColorLow",
  threeKaleidoscopeColorHigh: "wavedance.threeKaleidoscopeColorHigh",
  threeKaleidoscopeRotationSpeed: "wavedance.threeKaleidoscopeRotationSpeedDeg",
  threeKaleidoscopeReactiveness: "wavedance.threeKaleidoscopeReactiveness",
  threeKaleidoscopeBloom: "wavedance.threeKaleidoscopeBloomEnabled",
  threeKaleidoscopeBloomStrength: "wavedance.threeKaleidoscopeBloomStrength",
  threeKaleidoscopeShape: "wavedance.threeKaleidoscopeShapeConfig",
  threeGlitchBaseColor: "wavedance.threeGlitchSpectrumBaseColor",
  threeGlitchIntensity: "wavedance.threeGlitchSpectrumGlitchIntensity",
  threeGlitchRgbSplit: "wavedance.threeGlitchSpectrumRgbSplitPx",
  threeGlitchScanlineOpacity: "wavedance.threeGlitchSpectrumScanlineOpacity",
  threeGlitchTriggerThreshold: "wavedance.threeGlitchSpectrumTriggerThreshold",
  threeGlitchCooldownMs: "wavedance.threeGlitchSpectrumCooldownMs",
  threeGlitchShape: "wavedance.threeGlitchSpectrumShapeConfig",
  threePhosphorLineColor: "wavedance.threePhosphorTrailLineColor",
  threePhosphorLineWidth: "wavedance.threePhosphorTrailLineWidthPx",
  threePhosphorDecay: "wavedance.threePhosphorTrailDecayPercent",
  threePhosphorGlowColor: "wavedance.threePhosphorTrailGlowColor",
  threePhosphorBloom: "wavedance.threePhosphorTrailBloomEnabled",
  threePhosphorBloomStrength: "wavedance.threePhosphorTrailBloomStrength",
  threePhosphorMirror: "wavedance.threePhosphorTrailMirrorEnabled",
  threePhosphorShape: "wavedance.threePhosphorTrailShapeConfig",
  threeScanGridColor: "wavedance.threeScanGridGridColor",
  threeScanGridHighlightColor: "wavedance.threeScanGridHighlightColor",
  threeScanGridScanBeamColor: "wavedance.threeScanGridScanBeamColor",
  threeScanGridRows: "wavedance.threeScanGridGridRows",
  threeScanGridCols: "wavedance.threeScanGridGridCols",
  threeScanGridScanSpeed: "wavedance.threeScanGridScanSpeed",
  threeScanGridHighlightStrength: "wavedance.threeScanGridHighlightStrength",
  threeScanGridBloom: "wavedance.threeScanGridBloomEnabled",
  threeScanGridBloomStrength: "wavedance.threeScanGridBloomStrength",
  threeScanGridCameraPitch: "wavedance.threeScanGridCameraPitchDeg",
  threeScanGridShape: "wavedance.threeScanGridShapeConfig",
  threeLiquidBlobColor: "wavedance.threeLiquidBlobBlobColor",
  threeLiquidBlobColorSecondary: "wavedance.threeLiquidBlobBlobColorSecondary",
  threeLiquidBlobCount: "wavedance.threeLiquidBlobBlobCount",
  threeLiquidBlobMergeStrength: "wavedance.threeLiquidBlobMergeStrength",
  threeLiquidBlobWobbleSpeed: "wavedance.threeLiquidBlobWobbleSpeed",
  threeLiquidBlobBassDrive: "wavedance.threeLiquidBlobBassDrive",
  threeLiquidBlobBloom: "wavedance.threeLiquidBlobBloomEnabled",
  threeLiquidBlobBloomStrength: "wavedance.threeLiquidBlobBloomStrength",
  threeLiquidBlobShape: "wavedance.threeLiquidBlobShapeConfig",
  threeAuroraColorLow: "wavedance.threeAuroraRibbonColorLow",
  threeAuroraColorHigh: "wavedance.threeAuroraRibbonColorHigh",
  threeAuroraRibbonCount: "wavedance.threeAuroraRibbonRibbonCount",
  threeAuroraRibbonWidth: "wavedance.threeAuroraRibbonRibbonWidth",
  threeAuroraWaveAmplitude: "wavedance.threeAuroraRibbonWaveAmplitude",
  threeAuroraWaveSpeed: "wavedance.threeAuroraRibbonWaveSpeed",
  threeAuroraBassBandIndex: "wavedance.threeAuroraRibbonBassBandIndex",
  threeAuroraBloom: "wavedance.threeAuroraRibbonBloomEnabled",
  threeAuroraBloomStrength: "wavedance.threeAuroraRibbonBloomStrength",
  threeAuroraAutoRotateSpeed: "wavedance.threeAuroraRibbonAutoRotateSpeedDeg",
  threeAuroraShape: "wavedance.threeAuroraRibbonShapeConfig",
  threeBreathingRingColor: "wavedance.threeBreathingRingsRingColor",
  threeBreathingRingCount: "wavedance.threeBreathingRingsRingCount",
  threeBreathingBaseRadius: "wavedance.threeBreathingRingsBaseRadius",
  threeBreathingRadiusStep: "wavedance.threeBreathingRingsRadiusStep",
  threeBreathingPulseStrength: "wavedance.threeBreathingRingsPulseStrength",
  threeBreathingTubeRadius: "wavedance.threeBreathingRingsTubeRadius",
  threeBreathingBloom: "wavedance.threeBreathingRingsBloomEnabled",
  threeBreathingBloomStrength: "wavedance.threeBreathingRingsBloomStrength",
  threeBreathingAutoRotateSpeed: "wavedance.threeBreathingRingsAutoRotateSpeedDeg",
  threeBreathingShape: "wavedance.threeBreathingRingsShapeConfig",
  threeNoiseColorLow: "wavedance.threeNoiseLandscapeColorLow",
  threeNoiseColorHigh: "wavedance.threeNoiseLandscapeColorHigh",
  threeNoiseGridSize: "wavedance.threeNoiseLandscapeGridSize",
  threeNoiseHeightScale: "wavedance.threeNoiseLandscapeHeightScale",
  threeNoiseNoiseScale: "wavedance.threeNoiseLandscapeNoiseScale",
  threeNoiseScrollSpeed: "wavedance.threeNoiseLandscapeScrollSpeed",
  threeNoiseWireframe: "wavedance.threeNoiseLandscapeWireframeOverlay",
  threeNoiseBloom: "wavedance.threeNoiseLandscapeBloomEnabled",
  threeNoiseBloomStrength: "wavedance.threeNoiseLandscapeBloomStrength",
  threeNoiseCameraPitch: "wavedance.threeNoiseLandscapeCameraPitchDeg",
  threeNoiseShape: "wavedance.threeNoiseLandscapeShapeConfig",
  threeLavaLampColorWarm: "wavedance.threeLavaLampColorWarm",
  threeLavaLampColorCool: "wavedance.threeLavaLampColorCool",
  threeLavaLampBlobCount: "wavedance.threeLavaLampBlobCount",
  threeLavaLampMergeStrength: "wavedance.threeLavaLampMergeStrength",
  threeLavaLampBuoyancySpeed: "wavedance.threeLavaLampBuoyancySpeed",
  threeLavaLampBassDrive: "wavedance.threeLavaLampBassDrive",
  threeLavaLampBloom: "wavedance.threeLavaLampBloomEnabled",
  threeLavaLampBloomStrength: "wavedance.threeLavaLampBloomStrength",
  threeLavaLampShape: "wavedance.threeLavaLampShapeConfig",
  threeOilMarbleColor1: "wavedance.threeOilMarbleColor1",
  threeOilMarbleColor2: "wavedance.threeOilMarbleColor2",
  threeOilMarbleColor3: "wavedance.threeOilMarbleColor3",
  threeOilMarbleColor4: "wavedance.threeOilMarbleColor4",
  threeOilMarbleColor4Enabled: "wavedance.threeOilMarbleColor4Enabled",
  threeOilMarbleFlowSpeed: "wavedance.threeOilMarbleFlowSpeed",
  threeOilMarbleNoiseScale: "wavedance.threeOilMarbleNoiseScale",
  threeOilMarbleWarpStrength: "wavedance.threeOilMarbleWarpStrength",
  threeOilMarbleReactiveness: "wavedance.threeOilMarbleReactiveness",
  threeOilMarbleBloom: "wavedance.threeOilMarbleBloomEnabled",
  threeOilMarbleBloomStrength: "wavedance.threeOilMarbleBloomStrength",
  threeOilMarbleShape: "wavedance.threeOilMarbleShapeConfig",
  threePearlChainColor1: "wavedance.threePearlChainColor1",
  threePearlChainColor2: "wavedance.threePearlChainColor2",
  threePearlChainColor3: "wavedance.threePearlChainColor3",
  threePearlChainPearlCount: "wavedance.threePearlChainPearlCount",
  threePearlChainChainRadius: "wavedance.threePearlChainChainRadius",
  threePearlChainPearlSize: "wavedance.threePearlChainPearlSize",
  threePearlChainSwaySpeed: "wavedance.threePearlChainSwaySpeed",
  threePearlChainMergeStrength: "wavedance.threePearlChainMergeStrength",
  threePearlChainBloom: "wavedance.threePearlChainBloomEnabled",
  threePearlChainBloomStrength: "wavedance.threePearlChainBloomStrength",
  threePearlChainShape: "wavedance.threePearlChainShapeConfig",
  threeCrystalGemColorCore: "wavedance.threeCrystalGemColorCore",
  threeCrystalGemColorEdge: "wavedance.threeCrystalGemColorEdge",
  threeCrystalGemColorHighlight: "wavedance.threeCrystalGemColorHighlight",
  threeCrystalGemGemCount: "wavedance.threeCrystalGemGemCount",
  threeCrystalGemFacetSharpness: "wavedance.threeCrystalGemFacetSharpness",
  threeCrystalGemRotationSpeedDeg: "wavedance.threeCrystalGemRotationSpeedDeg",
  threeCrystalGemChromatic: "wavedance.threeCrystalGemChromaticEnabled",
  threeCrystalGemChromaticOffset: "wavedance.threeCrystalGemChromaticOffset",
  threeCrystalGemBloom: "wavedance.threeCrystalGemBloomEnabled",
  threeCrystalGemBloomStrength: "wavedance.threeCrystalGemBloomStrength",
  threeCrystalGemShape: "wavedance.threeCrystalGemShapeConfig",
  mainBgColor: "wavedance.mainBgColor",
  mainBgAlpha: "wavedance.mainBgAlpha",
  overlayBlur: "wavedance.overlayBlurEnabled",
};

export const DISPLAY_MODES = {
  line: "line",
  bar: "bar",
  area: "area",
  gradientBar: "gradientBar",
  glowLine: "glowLine",
  glowCircle: "glowCircle",
  radial: "radial",
  waterfall: "waterfall",
  dotRing: "dotRing",
  oscilloscope: "oscilloscope",
  obliqueBar: "obliqueBar",
  depthLayers: "depthLayers",
  isometricSkyline: "isometricSkyline",
  ring3d: "ring3d",
  terrain3d: "terrain3d",
  helix3d: "helix3d",
  threePlasmaField: "threePlasmaField",
  threeParticleGalaxy: "threeParticleGalaxy",
  threeBloomTunnel: "threeBloomTunnel",
  threeEnergySphere: "threeEnergySphere",
  threeKaleidoscope: "threeKaleidoscope",
  threeGlitchSpectrum: "threeGlitchSpectrum",
  threePhosphorTrail: "threePhosphorTrail",
  threeScanGrid: "threeScanGrid",
  threeLiquidBlob: "threeLiquidBlob",
  threeAuroraRibbon: "threeAuroraRibbon",
  threeBreathingRings: "threeBreathingRings",
  threeNoiseLandscape: "threeNoiseLandscape",
  threeLavaLamp: "threeLavaLamp",
  threeOilMarble: "threeOilMarble",
  threePearlChain: "threePearlChain",
  threeCrystalGem: "threeCrystalGem",
};

/** Three.js 高阶模式 id 列表（Phase 16 起逐步实现）。 */
export const THREE_DISPLAY_MODES = [
  DISPLAY_MODES.threePlasmaField,
  DISPLAY_MODES.threeParticleGalaxy,
  DISPLAY_MODES.threeBloomTunnel,
  DISPLAY_MODES.threeEnergySphere,
  DISPLAY_MODES.threeKaleidoscope,
  DISPLAY_MODES.threeGlitchSpectrum,
  DISPLAY_MODES.threePhosphorTrail,
  DISPLAY_MODES.threeScanGrid,
  DISPLAY_MODES.threeLiquidBlob,
  DISPLAY_MODES.threeAuroraRibbon,
  DISPLAY_MODES.threeBreathingRings,
  DISPLAY_MODES.threeNoiseLandscape,
  DISPLAY_MODES.threeLavaLamp,
  DISPLAY_MODES.threeOilMarble,
  DISPLAY_MODES.threePearlChain,
  DISPLAY_MODES.threeCrystalGem,
];

/** @param {string} mode */
export function isThreeDisplayMode(mode) {
  return THREE_DISPLAY_MODES.includes(String(mode ?? "").trim());
}

export const PANEL_STYLES = {
  pro: "pro",
  minimal: "minimal",
};

export const BAR_ORIENTATIONS = {
  horizontal: "horizontal",
  vertical: "vertical",
};

export const PEAK_HOLD_MODES = {
  off: "off",
  single: "single",
  both: "both",
};

export const DEFAULT_CONFIG = {
  displayMode: DISPLAY_MODES.line,
  panelStyleMode: PANEL_STYLES.pro,
  freqReversed: false,
  line: {
    color: "#c4a574",
    lineWidthPx: 2,
    shape: {
      gainPercent: 50,
      smoothPercent: 28,
      softClipPercent: 22,
      fallEasePercent: 68,
    },
  },
  bar: {
    color: "#8f7cff",
    widthPercent: 76,
    gapPercent: 18,
    headroomPercent: 6,
    orientation: BAR_ORIENTATIONS.horizontal,
    mirrorEnabled: false,
    peakHoldMode: PEAK_HOLD_MODES.single,
    peakColor: "#ffffff",
    peakFallSpeed: 35,
    peakThickness: 2,
    shape: {
      gainPercent: 62,
      smoothPercent: 18,
      softClipPercent: 12,
      fallEasePercent: 52,
    },
  },
  area: {
    fillColor: "#c4a574",
    fillAlphaPercent: 45,
    lineColor: "#c4a574",
    lineWidthPx: 2,
    mirrorEnabled: false,
    gradientEnabled: true,
    shape: {
      gainPercent: 50,
      smoothPercent: 28,
      softClipPercent: 22,
      fallEasePercent: 68,
    },
  },
  gradientBar: {
    colorLow: "#3b82f6",
    colorHigh: "#ec4899",
    widthPercent: 76,
    gapPercent: 18,
    headroomPercent: 6,
    orientation: BAR_ORIENTATIONS.horizontal,
    mirrorEnabled: false,
    peakHoldMode: PEAK_HOLD_MODES.single,
    peakColor: "#ffffff",
    peakFallSpeed: 35,
    peakThickness: 2,
    shape: {
      gainPercent: 62,
      smoothPercent: 18,
      softClipPercent: 12,
      fallEasePercent: 52,
    },
  },
  glowLine: {
    coreColor: "#c4a574",
    glowColor: "#c4a574",
    lineWidthPx: 2,
    glowRadiusPx: 8,
    glowIntensityPercent: 70,
    glowPasses: 4,
    shape: {
      gainPercent: 50,
      smoothPercent: 28,
      softClipPercent: 22,
      fallEasePercent: 68,
    },
  },
  glowCircle: {
    coreColor: "#c4a574",
    glowColor: "#c4a574",
    lineWidthPx: 2,
    glowRadiusPx: 8,
    glowIntensityPercent: 70,
    glowPasses: 4,
    ringRadiusPercent: 55,
    rotationOffsetDeg: 0,
    clockwise: true,
    shape: {
      gainPercent: 50,
      smoothPercent: 28,
      softClipPercent: 22,
      fallEasePercent: 68,
    },
  },
  radial: {
    barColor: "#8f7cff",
    innerRadiusPercent: 25,
    outerRadiusPercent: 90,
    barThicknessPercent: 70,
    mirrorEnabled: false,
    rotationOffsetDeg: 0,
    clockwise: true,
    shape: {
      gainPercent: 62,
      smoothPercent: 18,
      softClipPercent: 12,
      fallEasePercent: 52,
    },
  },
  waterfall: {
    colorLow: "#0a0a12",
    colorHigh: "#8f7cff",
    historyRows: 64,
    scrollEveryNFrames: 1,
    rowGapPercent: 0,
    shape: {
      gainPercent: 55,
      smoothPercent: 12,
      softClipPercent: 10,
      fallEasePercent: 40,
    },
  },
  dotRing: {
    dotColor: "#8f7cff",
    ringRadiusPercent: 75,
    dotCount: 32,
    dotSizePx: 6,
    pulseEnabled: true,
    shape: {
      gainPercent: 62,
      smoothPercent: 22,
      softClipPercent: 12,
      fallEasePercent: 55,
    },
  },
  oscilloscope: {
    lineColor: "#c4a574",
    lineWidthPx: 2,
    phosphorEnabled: false,
    phosphorDecayPercent: 60,
  },
  obliqueBar: {
    barColor: "#8f7cff",
    barColorFar: "#4a4580",
    widthPercent: 76,
    gapPercent: 18,
    headroomPercent: 8,
    tiltDeg: 55,
    showGroundLine: true,
    mirrorEnabled: false,
    displayBarCount: 0,
    shape: {
      gainPercent: 62,
      smoothPercent: 18,
      softClipPercent: 12,
      fallEasePercent: 52,
    },
  },
  depthLayers: {
    layerCount: 4,
    color: "#8f7cff",
    colorFar: "#3d3866",
    layerSpacingPx: 6,
    farScalePercent: 72,
    farAlphaPercent: 25,
    bassFrontEnabled: true,
    lineWidthPx: 2,
    renderStyle: "line",
    shape: {
      gainPercent: 55,
      smoothPercent: 24,
      softClipPercent: 14,
      fallEasePercent: 58,
    },
  },
  isometricSkyline: {
    faceTopColor: "#8f7cff",
    faceLeftColor: "#6b5fd4",
    faceRightColor: "#a898ff",
    buildingWidthPx: 8,
    buildingGapPx: 2,
    skylineBaselinePercent: 15,
    displayBuildingCount: 48,
    showGroundPlane: true,
    shape: {
      gainPercent: 60,
      smoothPercent: 16,
      softClipPercent: 10,
      fallEasePercent: 50,
    },
  },
  ring3d: {
    barColor: "#8f7cff",
    innerRadius: 0.35,
    outerRadius: 0.95,
    barHeightScale: 0.8,
    barThicknessDeg: 4,
    displayBarCount: 48,
    wireframeEnabled: true,
    fillEnabled: false,
    autoRotateEnabled: true,
    autoRotateSpeedDeg: 6,
    cameraDistance: 2.2,
    cameraFovDeg: 45,
    breatheWithPeak: true,
    shape: {
      gainPercent: 62,
      smoothPercent: 18,
      softClipPercent: 12,
      fallEasePercent: 52,
    },
  },
  terrain3d: {
    colorLow: "#1a1a2e",
    colorHigh: "#8f7cff",
    wireframeColor: "#c4b5fd",
    gridCols: 64,
    gridRows: 48,
    scrollEveryNFrames: 1,
    wireframeEnabled: true,
    fillEnabled: false,
    terrainHeightScale: 0.35,
    cameraPitchDeg: 55,
    cameraDistance: 2.8,
    autoScrollEnabled: true,
    shape: {
      gainPercent: 55,
      smoothPercent: 12,
      softClipPercent: 10,
      fallEasePercent: 40,
    },
  },
  helix3d: {
    dotColor: "#8f7cff",
    helixRadius: 0.5,
    helixPitch: 0.35,
    helixTurns: 2.5,
    displayPointCount: 32,
    extrudeMode: "radial",
    pointSizePx: 8,
    wireframeEnabled: true,
    autoRotateEnabled: true,
    autoRotateSpeedDeg: 8,
    cameraDistance: 2.5,
    cameraFovDeg: 45,
    shape: {
      gainPercent: 62,
      smoothPercent: 20,
      softClipPercent: 12,
      fallEasePercent: 55,
    },
  },
  threePlasmaField: {
    colorLow: "#1a0533",
    colorHigh: "#8f7cff",
    speed: 1.0,
    noiseScale: 2.5,
    reactiveness: 70,
    bloomEnabled: true,
    bloomStrength: 0.8,
    shape: {
      gainPercent: 55,
      smoothPercent: 16,
      softClipPercent: 10,
      fallEasePercent: 50,
    },
  },
  threeParticleGalaxy: {
    particleColor: "#c4b5fd",
    particleCount: 12000,
    galaxyRadius: 1.2,
    spiralArms: 2,
    bassPullStrength: 65,
    trebleSpreadStrength: 55,
    bloomEnabled: true,
    bloomStrength: 1.2,
    autoRotateSpeedDeg: 4,
    shape: {
      gainPercent: 60,
      smoothPercent: 20,
      softClipPercent: 12,
      fallEasePercent: 55,
    },
  },
  threeBloomTunnel: {
    wallColorLow: "#1a1a2e",
    wallColorHigh: "#8f7cff",
    coreColor: "#ffffff",
    tunnelSpeed: 1.0,
    wallSegments: 48,
    corePulseStrength: 70,
    bloomEnabled: true,
    bloomStrength: 1.0,
    fovDeg: 60,
    shape: {
      gainPercent: 58,
      smoothPercent: 14,
      softClipPercent: 10,
      fallEasePercent: 45,
    },
  },
  threeEnergySphere: {
    coreColor: "#8f7cff",
    haloColor: "#c4b5fd",
    deformStrength: 75,
    noiseSpeed: 1.2,
    haloParticleCount: 800,
    wireframeOverlay: false,
    bloomEnabled: true,
    bloomStrength: 1.0,
    autoRotateSpeedDeg: 6,
    shape: {
      gainPercent: 62,
      smoothPercent: 18,
      softClipPercent: 12,
      fallEasePercent: 52,
    },
  },
  threeKaleidoscope: {
    segments: 8,
    colorLow: "#3b82f6",
    colorHigh: "#ec4899",
    rotationSpeedDeg: 8,
    reactiveness: 75,
    bloomEnabled: true,
    bloomStrength: 0.6,
    shape: {
      gainPercent: 55,
      smoothPercent: 20,
      softClipPercent: 12,
      fallEasePercent: 55,
    },
  },
  threeGlitchSpectrum: {
    baseColor: "#8f7cff",
    glitchIntensity: 60,
    rgbSplitPx: 4,
    scanlineOpacity: 25,
    triggerThreshold: 55,
    cooldownMs: 120,
    shape: {
      gainPercent: 60,
      smoothPercent: 12,
      softClipPercent: 8,
      fallEasePercent: 40,
    },
  },
  threePhosphorTrail: {
    lineColor: "#c4a574",
    lineWidthPx: 3,
    decayPercent: 55,
    glowColor: "#8f7cff",
    bloomEnabled: true,
    bloomStrength: 0.9,
    mirrorEnabled: false,
    shape: {
      gainPercent: 50,
      smoothPercent: 22,
      softClipPercent: 14,
      fallEasePercent: 60,
    },
  },
  threeScanGrid: {
    gridColor: "#4a4580",
    highlightColor: "#8f7cff",
    scanBeamColor: "#ffffff",
    gridRows: 32,
    gridCols: 48,
    scanSpeed: 1.0,
    highlightStrength: 70,
    bloomEnabled: true,
    bloomStrength: 0.7,
    cameraPitchDeg: 50,
    shape: {
      gainPercent: 58,
      smoothPercent: 14,
      softClipPercent: 10,
      fallEasePercent: 48,
    },
  },
  threeLiquidBlob: {
    blobColor: "#8f7cff",
    blobColorSecondary: "#ec4899",
    blobCount: 3,
    mergeStrength: 65,
    wobbleSpeed: 1.0,
    bassDrive: 75,
    bloomEnabled: true,
    bloomStrength: 0.8,
    shape: {
      gainPercent: 62,
      smoothPercent: 22,
      softClipPercent: 14,
      fallEasePercent: 55,
    },
  },
  threeAuroraRibbon: {
    ribbonCount: 4,
    colorLow: "#3b82f6",
    colorHigh: "#a855f7",
    ribbonWidth: 0.08,
    waveAmplitude: 0.35,
    waveSpeed: 1.0,
    bassBandIndex: 0,
    bloomEnabled: true,
    bloomStrength: 1.0,
    autoRotateSpeedDeg: 3,
    shape: {
      gainPercent: 58,
      smoothPercent: 24,
      softClipPercent: 14,
      fallEasePercent: 58,
    },
  },
  threeBreathingRings: {
    ringColor: "#8f7cff",
    ringCount: 5,
    baseRadius: 0.4,
    radiusStep: 0.15,
    pulseStrength: 70,
    tubeRadius: 0.02,
    bloomEnabled: true,
    bloomStrength: 0.9,
    autoRotateSpeedDeg: 5,
    shape: {
      gainPercent: 55,
      smoothPercent: 20,
      softClipPercent: 12,
      fallEasePercent: 52,
    },
  },
  threeNoiseLandscape: {
    colorLow: "#1a1a2e",
    colorHigh: "#8f7cff",
    gridSize: 64,
    heightScale: 0.4,
    noiseScale: 1.8,
    scrollSpeed: 0.6,
    wireframeOverlay: true,
    bloomEnabled: false,
    bloomStrength: 0.7,
    cameraPitchDeg: 55,
    shape: {
      gainPercent: 55,
      smoothPercent: 16,
      softClipPercent: 10,
      fallEasePercent: 45,
    },
  },
  threeLavaLamp: {
    colorWarm: "#ff6b35",
    colorCool: "#8f7cff",
    blobCount: 3,
    mergeStrength: 70,
    buoyancySpeed: 0.65,
    lampAspect: 0.55,
    bassDrive: 80,
    bloomEnabled: true,
    bloomStrength: 0.85,
    shape: {
      gainPercent: 58,
      smoothPercent: 24,
      softClipPercent: 14,
      fallEasePercent: 58,
    },
  },
  threeOilMarble: {
    color1: "#8f7cff",
    color2: "#ec4899",
    color3: "#3b82f6",
    color4: "#14b8a6",
    color4Enabled: true,
    flowSpeed: 1.0,
    noiseScale: 2.2,
    warpStrength: 65,
    reactiveness: 70,
    bloomEnabled: true,
    bloomStrength: 0.75,
    shape: {
      gainPercent: 55,
      smoothPercent: 20,
      softClipPercent: 12,
      fallEasePercent: 55,
    },
  },
  threePearlChain: {
    color1: "#f5e6d3",
    color2: "#c4b5fd",
    color3: "#8f7cff",
    pearlCount: 7,
    chainRadius: 0.75,
    pearlSize: 0.22,
    swaySpeed: 0.8,
    mergeStrength: 45,
    bloomEnabled: true,
    bloomStrength: 0.9,
    shape: {
      gainPercent: 60,
      smoothPercent: 22,
      softClipPercent: 12,
      fallEasePercent: 55,
    },
  },
  threeCrystalGem: {
    colorCore: "#8f7cff",
    colorEdge: "#ec4899",
    colorHighlight: "#ffffff",
    gemCount: 1,
    facetSharpness: 65,
    rotationSpeedDeg: 5,
    chromaticEnabled: true,
    chromaticOffset: 0.003,
    bloomEnabled: true,
    bloomStrength: 1.0,
    shape: {
      gainPercent: 62,
      smoothPercent: 18,
      softClipPercent: 12,
      fallEasePercent: 52,
    },
  },
};

/** @param {string} mode */
export function normalizeDisplayMode(mode) {
  const s = String(mode ?? "").trim();
  if (s === DISPLAY_MODES.bar) return DISPLAY_MODES.bar;
  if (s === DISPLAY_MODES.area) return DISPLAY_MODES.area;
  if (s === DISPLAY_MODES.gradientBar) return DISPLAY_MODES.gradientBar;
  if (s === DISPLAY_MODES.glowLine) return DISPLAY_MODES.glowLine;
  if (s === DISPLAY_MODES.glowCircle) return DISPLAY_MODES.glowCircle;
  if (s === DISPLAY_MODES.radial) return DISPLAY_MODES.radial;
  if (s === DISPLAY_MODES.waterfall) return DISPLAY_MODES.waterfall;
  if (s === DISPLAY_MODES.dotRing) return DISPLAY_MODES.dotRing;
  if (s === DISPLAY_MODES.oscilloscope) return DISPLAY_MODES.oscilloscope;
  if (s === DISPLAY_MODES.obliqueBar) return DISPLAY_MODES.obliqueBar;
  if (s === DISPLAY_MODES.depthLayers) return DISPLAY_MODES.depthLayers;
  if (s === DISPLAY_MODES.isometricSkyline) return DISPLAY_MODES.isometricSkyline;
  if (s === DISPLAY_MODES.ring3d) return DISPLAY_MODES.ring3d;
  if (s === DISPLAY_MODES.terrain3d) return DISPLAY_MODES.terrain3d;
  if (s === DISPLAY_MODES.helix3d) return DISPLAY_MODES.helix3d;
  if (s === DISPLAY_MODES.threePlasmaField) return DISPLAY_MODES.threePlasmaField;
  if (s === DISPLAY_MODES.threeParticleGalaxy) return DISPLAY_MODES.threeParticleGalaxy;
  if (s === DISPLAY_MODES.threeBloomTunnel) return DISPLAY_MODES.threeBloomTunnel;
  if (s === DISPLAY_MODES.threeEnergySphere) return DISPLAY_MODES.threeEnergySphere;
  if (s === DISPLAY_MODES.threeKaleidoscope) return DISPLAY_MODES.threeKaleidoscope;
  if (s === DISPLAY_MODES.threeGlitchSpectrum) return DISPLAY_MODES.threeGlitchSpectrum;
  if (s === DISPLAY_MODES.threePhosphorTrail) return DISPLAY_MODES.threePhosphorTrail;
  if (s === DISPLAY_MODES.threeScanGrid) return DISPLAY_MODES.threeScanGrid;
  if (s === DISPLAY_MODES.threeLiquidBlob) return DISPLAY_MODES.threeLiquidBlob;
  if (s === DISPLAY_MODES.threeAuroraRibbon) return DISPLAY_MODES.threeAuroraRibbon;
  if (s === DISPLAY_MODES.threeBreathingRings) return DISPLAY_MODES.threeBreathingRings;
  if (s === DISPLAY_MODES.threeNoiseLandscape) return DISPLAY_MODES.threeNoiseLandscape;
  if (s === DISPLAY_MODES.threeLavaLamp) return DISPLAY_MODES.threeLavaLamp;
  if (s === DISPLAY_MODES.threeOilMarble) return DISPLAY_MODES.threeOilMarble;
  if (s === DISPLAY_MODES.threePearlChain) return DISPLAY_MODES.threePearlChain;
  if (s === DISPLAY_MODES.threeCrystalGem) return DISPLAY_MODES.threeCrystalGem;
  return DISPLAY_MODES.line;
}

/** @param {string | number} value @param {number} [fallback=8] */
export function normalizeKaleidoscopeSegments(value, fallback = 8) {
  const n = Math.round(Number(value));
  if (!Number.isFinite(n)) return fallback;
  const clamped = Math.min(12, Math.max(4, n));
  return clamped % 2 === 0 ? clamped : clamped - 1;
}

/** @param {string} value */
export function normalizeHelix3dExtrudeMode(value, fallback = "radial") {
  const s = String(value ?? "").trim();
  if (s === "height") return "height";
  if (s === "radial") return "radial";
  return fallback;
}

/** @param {string} value */
export function normalizeDepthLayersRenderStyle(value, fallback = "line") {
  const s = String(value ?? "").trim();
  if (s === "bar") return "bar";
  if (s === "line") return "line";
  return fallback;
}

export function clampInt(value, min, max) {
  const n = Math.round(Number(value));
  if (!Number.isFinite(n)) return min;
  return Math.min(max, Math.max(min, n));
}

export function parseBoolean(value, fallback = false) {
  if (typeof value === "boolean") return value;
  if (value === "true") return true;
  if (value === "false") return false;
  return fallback;
}

export function normalizeBarOrientation(value, fallback = BAR_ORIENTATIONS.horizontal) {
  const s = String(value ?? "").trim();
  if (s === BAR_ORIENTATIONS.vertical) return BAR_ORIENTATIONS.vertical;
  if (s === BAR_ORIENTATIONS.horizontal) return BAR_ORIENTATIONS.horizontal;
  return fallback;
}

export function normalizeBarPeakHoldMode(value, fallback = PEAK_HOLD_MODES.single) {
  const s = String(value ?? "").trim();
  if (s === PEAK_HOLD_MODES.off) return PEAK_HOLD_MODES.off;
  if (s === PEAK_HOLD_MODES.both) return PEAK_HOLD_MODES.both;
  if (s === PEAK_HOLD_MODES.single) return PEAK_HOLD_MODES.single;
  return fallback;
}

/**
 * 读取峰值保持线模式；兼容旧版 boolean 存储 `barPeakHold`。
 * @param {Storage} ls
 * @param {string} windowLabel
 */
export function readBarPeakHoldMode(ls, windowLabel) {
  const modeRaw = readWindowStorageString(ls, windowLabel, "barPeakHoldMode");
  if (modeRaw === PEAK_HOLD_MODES.off || modeRaw === PEAK_HOLD_MODES.single || modeRaw === PEAK_HOLD_MODES.both) {
    return modeRaw;
  }
  const legacyRaw = readWindowStorageString(ls, windowLabel, "barPeakHold");
  if (legacyRaw != null && legacyRaw !== "") {
    return parseBoolean(legacyRaw, true) ? PEAK_HOLD_MODES.single : PEAK_HOLD_MODES.off;
  }
  return DEFAULT_CONFIG.bar.peakHoldMode;
}

/**
 * 读取渐变频谱柱峰值保持线模式；兼容旧版 boolean 存储 `gradientBarPeakHold`。
 * @param {Storage} ls
 * @param {string} windowLabel
 */
export function readGradientBarPeakHoldMode(ls, windowLabel) {
  const modeRaw = readWindowStorageString(ls, windowLabel, "gradientBarPeakHoldMode");
  if (modeRaw === PEAK_HOLD_MODES.off || modeRaw === PEAK_HOLD_MODES.single || modeRaw === PEAK_HOLD_MODES.both) {
    return modeRaw;
  }
  const legacyRaw = readWindowStorageString(ls, windowLabel, "gradientBarPeakHold");
  if (legacyRaw != null && legacyRaw !== "") {
    return parseBoolean(legacyRaw, true) ? PEAK_HOLD_MODES.single : PEAK_HOLD_MODES.off;
  }
  return DEFAULT_CONFIG.gradientBar.peakHoldMode;
}

/** 仅允许主窗与频谱副窗作为「每窗配置」的存储分区。 */
export function normalizeSpectrumWindowLabel(label) {
  const s = String(label ?? "").trim();
  if (s === "main" || s.startsWith("spectrum-")) {
    return s;
  }
  return "main";
}

/**
 * 各频谱窗口独立的外观/形态 localStorage 键（与 {@link STORAGE_KEYS} 字段一一对应）。
 * 旧版未带窗口 id 的键仍会通过 {@link readWindowStorageString} 回退读取。
 */
export function windowStorageKeys(windowLabel) {
  const id = normalizeSpectrumWindowLabel(windowLabel);
  const pre = `wavedance.win.${id}`;
  return {
    lineShape: `${pre}.waveShapeConfig`,
    barShape: `${pre}.barShapeConfig`,
    displayMode: `${pre}.displayMode`,
    panelStyleMode: `${pre}.panelStyleMode`,
    freqReversed: `${pre}.freqReversed`,
    lineColor: `${pre}.lineColor`,
    lineWidth: `${pre}.lineWidthPx`,
    barColor: `${pre}.barColor`,
    barWidth: `${pre}.barWidthPercent`,
    barGap: `${pre}.barGapPercent`,
    barHeadroom: `${pre}.barHeadroomPercent`,
    barOrientation: `${pre}.barOrientation`,
    barMirror: `${pre}.barMirrorEnabled`,
    barPeakHold: `${pre}.barPeakHoldEnabled`,
    barPeakHoldMode: `${pre}.barPeakHoldMode`,
    barPeakColor: `${pre}.barPeakColor`,
    barPeakFallSpeed: `${pre}.barPeakFallSpeed`,
    barPeakThickness: `${pre}.barPeakThickness`,
    areaColor: `${pre}.areaFillColor`,
    areaLineColor: `${pre}.areaLineColor`,
    areaFillAlpha: `${pre}.areaFillAlphaPercent`,
    areaLineWidth: `${pre}.areaLineWidthPx`,
    areaMirror: `${pre}.areaMirrorEnabled`,
    areaGradient: `${pre}.areaGradientEnabled`,
    areaShape: `${pre}.areaShapeConfig`,
    gradientBarColorLow: `${pre}.gradientBarColorLow`,
    gradientBarColorHigh: `${pre}.gradientBarColorHigh`,
    gradientBarWidth: `${pre}.gradientBarWidthPercent`,
    gradientBarGap: `${pre}.gradientBarGapPercent`,
    gradientBarHeadroom: `${pre}.gradientBarHeadroomPercent`,
    gradientBarOrientation: `${pre}.gradientBarOrientation`,
    gradientBarMirror: `${pre}.gradientBarMirrorEnabled`,
    gradientBarPeakHoldMode: `${pre}.gradientBarPeakHoldMode`,
    gradientBarPeakColor: `${pre}.gradientBarPeakColor`,
    gradientBarPeakFallSpeed: `${pre}.gradientBarPeakFallSpeed`,
    gradientBarPeakThickness: `${pre}.gradientBarPeakThickness`,
    gradientBarShape: `${pre}.gradientBarShapeConfig`,
    glowLineCoreColor: `${pre}.glowLineCoreColor`,
    glowLineGlowColor: `${pre}.glowLineGlowColor`,
    glowLineWidth: `${pre}.glowLineWidthPx`,
    glowLineGlowRadius: `${pre}.glowLineGlowRadiusPx`,
    glowLineGlowIntensity: `${pre}.glowLineGlowIntensityPercent`,
    glowLineShape: `${pre}.glowLineShapeConfig`,
    glowCircleCoreColor: `${pre}.glowCircleCoreColor`,
    glowCircleGlowColor: `${pre}.glowCircleGlowColor`,
    glowCircleWidth: `${pre}.glowCircleWidthPx`,
    glowCircleGlowRadius: `${pre}.glowCircleGlowRadiusPx`,
    glowCircleGlowIntensity: `${pre}.glowCircleGlowIntensityPercent`,
    glowCircleShape: `${pre}.glowCircleShapeConfig`,
    glowCircleRingRadius: `${pre}.glowCircleRingRadiusPercent`,
    glowCircleRotation: `${pre}.glowCircleRotationOffsetDeg`,
    glowCircleClockwise: `${pre}.glowCircleClockwise`,
    radialColor: `${pre}.radialBarColor`,
    radialInnerRadius: `${pre}.radialInnerRadiusPercent`,
    radialOuterRadius: `${pre}.radialOuterRadiusPercent`,
    radialBarThickness: `${pre}.radialBarThicknessPercent`,
    radialMirror: `${pre}.radialMirrorEnabled`,
    radialRotation: `${pre}.radialRotationOffsetDeg`,
    radialClockwise: `${pre}.radialClockwise`,
    radialShape: `${pre}.radialShapeConfig`,
    waterfallColorLow: `${pre}.waterfallColorLow`,
    waterfallColorHigh: `${pre}.waterfallColorHigh`,
    waterfallHistoryRows: `${pre}.waterfallHistoryRows`,
    waterfallScrollEveryNFrames: `${pre}.waterfallScrollEveryNFrames`,
    waterfallRowGap: `${pre}.waterfallRowGapPercent`,
    waterfallShape: `${pre}.waterfallShapeConfig`,
    dotRingColor: `${pre}.dotRingDotColor`,
    dotRingRadius: `${pre}.dotRingRadiusPercent`,
    dotRingCount: `${pre}.dotRingDotCount`,
    dotRingSize: `${pre}.dotRingDotSizePx`,
    dotRingPulse: `${pre}.dotRingPulseEnabled`,
    dotRingShape: `${pre}.dotRingShapeConfig`,
    oscilloscopeColor: `${pre}.oscilloscopeLineColor`,
    oscilloscopeLineWidth: `${pre}.oscilloscopeLineWidthPx`,
    oscilloscopePhosphor: `${pre}.oscilloscopePhosphorEnabled`,
    oscilloscopePhosphorDecay: `${pre}.oscilloscopePhosphorDecayPercent`,
    obliqueBarColor: `${pre}.obliqueBarColor`,
    obliqueBarColorFar: `${pre}.obliqueBarColorFar`,
    obliqueBarWidth: `${pre}.obliqueBarWidthPercent`,
    obliqueBarGap: `${pre}.obliqueBarGapPercent`,
    obliqueBarHeadroom: `${pre}.obliqueBarHeadroomPercent`,
    obliqueBarTilt: `${pre}.obliqueBarTiltDeg`,
    obliqueBarGroundLine: `${pre}.obliqueBarShowGroundLine`,
    obliqueBarMirror: `${pre}.obliqueBarMirrorEnabled`,
    obliqueBarDisplayCount: `${pre}.obliqueBarDisplayBarCount`,
    obliqueBarShape: `${pre}.obliqueBarShapeConfig`,
    depthLayersCount: `${pre}.depthLayersLayerCount`,
    depthLayersSpacing: `${pre}.depthLayersLayerSpacingPx`,
    depthLayersFarScale: `${pre}.depthLayersFarScalePercent`,
    depthLayersFarAlpha: `${pre}.depthLayersFarAlphaPercent`,
    depthLayersBassFront: `${pre}.depthLayersBassFrontEnabled`,
    depthLayersColor: `${pre}.depthLayersColor`,
    depthLayersColorFar: `${pre}.depthLayersColorFar`,
    depthLayersLineWidth: `${pre}.depthLayersLineWidthPx`,
    depthLayersRenderStyle: `${pre}.depthLayersRenderStyle`,
    depthLayersShape: `${pre}.depthLayersShapeConfig`,
    isometricSkylineFaceTop: `${pre}.isometricSkylineFaceTopColor`,
    isometricSkylineFaceLeft: `${pre}.isometricSkylineFaceLeftColor`,
    isometricSkylineFaceRight: `${pre}.isometricSkylineFaceRightColor`,
    isometricSkylineBuildingWidth: `${pre}.isometricSkylineBuildingWidthPx`,
    isometricSkylineBuildingGap: `${pre}.isometricSkylineBuildingGapPx`,
    isometricSkylineBaseline: `${pre}.isometricSkylineBaselinePercent`,
    isometricSkylineBuildingCount: `${pre}.isometricSkylineDisplayBuildingCount`,
    isometricSkylineGroundPlane: `${pre}.isometricSkylineShowGroundPlane`,
    isometricSkylineShape: `${pre}.isometricSkylineShapeConfig`,
    ring3dColor: `${pre}.ring3dBarColor`,
    ring3dInnerRadius: `${pre}.ring3dInnerRadius`,
    ring3dOuterRadius: `${pre}.ring3dOuterRadius`,
    ring3dBarHeightScale: `${pre}.ring3dBarHeightScale`,
    ring3dBarThicknessDeg: `${pre}.ring3dBarThicknessDeg`,
    ring3dDisplayCount: `${pre}.ring3dDisplayBarCount`,
    ring3dWireframe: `${pre}.ring3dWireframeEnabled`,
    ring3dFill: `${pre}.ring3dFillEnabled`,
    ring3dAutoRotate: `${pre}.ring3dAutoRotateEnabled`,
    ring3dAutoRotateSpeed: `${pre}.ring3dAutoRotateSpeedDeg`,
    ring3dCameraDistance: `${pre}.ring3dCameraDistance`,
    ring3dCameraFov: `${pre}.ring3dCameraFovDeg`,
    ring3dBreathePeak: `${pre}.ring3dBreatheWithPeak`,
    ring3dShape: `${pre}.ring3dShapeConfig`,
    terrain3dColorLow: `${pre}.terrain3dColorLow`,
    terrain3dColorHigh: `${pre}.terrain3dColorHigh`,
    terrain3dWireframeColor: `${pre}.terrain3dWireframeColor`,
    terrain3dGridCols: `${pre}.terrain3dGridCols`,
    terrain3dGridRows: `${pre}.terrain3dGridRows`,
    terrain3dScrollEveryNFrames: `${pre}.terrain3dScrollEveryNFrames`,
    terrain3dWireframe: `${pre}.terrain3dWireframeEnabled`,
    terrain3dFill: `${pre}.terrain3dFillEnabled`,
    terrain3dHeightScale: `${pre}.terrain3dTerrainHeightScale`,
    terrain3dCameraPitch: `${pre}.terrain3dCameraPitchDeg`,
    terrain3dCameraDistance: `${pre}.terrain3dCameraDistance`,
    terrain3dAutoScroll: `${pre}.terrain3dAutoScrollEnabled`,
    terrain3dShape: `${pre}.terrain3dShapeConfig`,
    helix3dColor: `${pre}.helix3dDotColor`,
    helix3dRadius: `${pre}.helix3dHelixRadius`,
    helix3dPitch: `${pre}.helix3dHelixPitch`,
    helix3dTurns: `${pre}.helix3dHelixTurns`,
    helix3dDisplayCount: `${pre}.helix3dDisplayPointCount`,
    helix3dExtrudeMode: `${pre}.helix3dExtrudeMode`,
    helix3dPointSize: `${pre}.helix3dPointSizePx`,
    helix3dWireframe: `${pre}.helix3dWireframeEnabled`,
    helix3dAutoRotate: `${pre}.helix3dAutoRotateEnabled`,
    helix3dAutoRotateSpeed: `${pre}.helix3dAutoRotateSpeedDeg`,
    helix3dCameraDistance: `${pre}.helix3dCameraDistance`,
    helix3dCameraFov: `${pre}.helix3dCameraFovDeg`,
    helix3dShape: `${pre}.helix3dShapeConfig`,
    threePlasmaColorLow: `${pre}.threePlasmaColorLow`,
    threePlasmaColorHigh: `${pre}.threePlasmaColorHigh`,
    threePlasmaSpeed: `${pre}.threePlasmaSpeed`,
    threePlasmaNoiseScale: `${pre}.threePlasmaNoiseScale`,
    threePlasmaReactiveness: `${pre}.threePlasmaReactiveness`,
    threePlasmaBloom: `${pre}.threePlasmaBloomEnabled`,
    threePlasmaBloomStrength: `${pre}.threePlasmaBloomStrength`,
    threePlasmaShape: `${pre}.threePlasmaShapeConfig`,
    threeGalaxyColor: `${pre}.threeGalaxyParticleColor`,
    threeGalaxyCount: `${pre}.threeGalaxyParticleCount`,
    threeGalaxyRadius: `${pre}.threeGalaxyRadius`,
    threeGalaxyArms: `${pre}.threeGalaxySpiralArms`,
    threeGalaxyBassPull: `${pre}.threeGalaxyBassPullStrength`,
    threeGalaxyTrebleSpread: `${pre}.threeGalaxyTrebleSpreadStrength`,
    threeGalaxyBloom: `${pre}.threeGalaxyBloomEnabled`,
    threeGalaxyBloomStrength: `${pre}.threeGalaxyBloomStrength`,
    threeGalaxyAutoRotateSpeed: `${pre}.threeGalaxyAutoRotateSpeedDeg`,
    threeGalaxyShape: `${pre}.threeGalaxyShapeConfig`,
    threeTunnelWallColorLow: `${pre}.threeTunnelWallColorLow`,
    threeTunnelWallColorHigh: `${pre}.threeTunnelWallColorHigh`,
    threeTunnelCoreColor: `${pre}.threeTunnelCoreColor`,
    threeTunnelSpeed: `${pre}.threeTunnelSpeed`,
    threeTunnelWallSegments: `${pre}.threeTunnelWallSegments`,
    threeTunnelCorePulseStrength: `${pre}.threeTunnelCorePulseStrength`,
    threeTunnelBloom: `${pre}.threeTunnelBloomEnabled`,
    threeTunnelBloomStrength: `${pre}.threeTunnelBloomStrength`,
    threeTunnelFov: `${pre}.threeTunnelFovDeg`,
    threeTunnelShape: `${pre}.threeTunnelShapeConfig`,
    threeSphereCoreColor: `${pre}.threeSphereCoreColor`,
    threeSphereHaloColor: `${pre}.threeSphereHaloColor`,
    threeSphereDeformStrength: `${pre}.threeSphereDeformStrength`,
    threeSphereNoiseSpeed: `${pre}.threeSphereNoiseSpeed`,
    threeSphereHaloCount: `${pre}.threeSphereHaloParticleCount`,
    threeSphereWireframe: `${pre}.threeSphereWireframeOverlay`,
    threeSphereBloom: `${pre}.threeSphereBloomEnabled`,
    threeSphereBloomStrength: `${pre}.threeSphereBloomStrength`,
    threeSphereAutoRotateSpeed: `${pre}.threeSphereAutoRotateSpeedDeg`,
    threeSphereShape: `${pre}.threeSphereShapeConfig`,
    threeKaleidoscopeSegments: `${pre}.threeKaleidoscopeSegments`,
    threeKaleidoscopeColorLow: `${pre}.threeKaleidoscopeColorLow`,
    threeKaleidoscopeColorHigh: `${pre}.threeKaleidoscopeColorHigh`,
    threeKaleidoscopeRotationSpeed: `${pre}.threeKaleidoscopeRotationSpeedDeg`,
    threeKaleidoscopeReactiveness: `${pre}.threeKaleidoscopeReactiveness`,
    threeKaleidoscopeBloom: `${pre}.threeKaleidoscopeBloomEnabled`,
    threeKaleidoscopeBloomStrength: `${pre}.threeKaleidoscopeBloomStrength`,
    threeKaleidoscopeShape: `${pre}.threeKaleidoscopeShapeConfig`,
    threeGlitchBaseColor: `${pre}.threeGlitchSpectrumBaseColor`,
    threeGlitchIntensity: `${pre}.threeGlitchSpectrumGlitchIntensity`,
    threeGlitchRgbSplit: `${pre}.threeGlitchSpectrumRgbSplitPx`,
    threeGlitchScanlineOpacity: `${pre}.threeGlitchSpectrumScanlineOpacity`,
    threeGlitchTriggerThreshold: `${pre}.threeGlitchSpectrumTriggerThreshold`,
    threeGlitchCooldownMs: `${pre}.threeGlitchSpectrumCooldownMs`,
    threeGlitchShape: `${pre}.threeGlitchSpectrumShapeConfig`,
    threePhosphorLineColor: `${pre}.threePhosphorTrailLineColor`,
    threePhosphorLineWidth: `${pre}.threePhosphorTrailLineWidthPx`,
    threePhosphorDecay: `${pre}.threePhosphorTrailDecayPercent`,
    threePhosphorGlowColor: `${pre}.threePhosphorTrailGlowColor`,
    threePhosphorBloom: `${pre}.threePhosphorTrailBloomEnabled`,
    threePhosphorBloomStrength: `${pre}.threePhosphorTrailBloomStrength`,
    threePhosphorMirror: `${pre}.threePhosphorTrailMirrorEnabled`,
    threePhosphorShape: `${pre}.threePhosphorTrailShapeConfig`,
    threeScanGridColor: `${pre}.threeScanGridGridColor`,
    threeScanGridHighlightColor: `${pre}.threeScanGridHighlightColor`,
    threeScanGridScanBeamColor: `${pre}.threeScanGridScanBeamColor`,
    threeScanGridRows: `${pre}.threeScanGridGridRows`,
    threeScanGridCols: `${pre}.threeScanGridGridCols`,
    threeScanGridScanSpeed: `${pre}.threeScanGridScanSpeed`,
    threeScanGridHighlightStrength: `${pre}.threeScanGridHighlightStrength`,
    threeScanGridBloom: `${pre}.threeScanGridBloomEnabled`,
    threeScanGridBloomStrength: `${pre}.threeScanGridBloomStrength`,
    threeScanGridCameraPitch: `${pre}.threeScanGridCameraPitchDeg`,
    threeScanGridShape: `${pre}.threeScanGridShapeConfig`,
    threeLiquidBlobColor: `${pre}.threeLiquidBlobBlobColor`,
    threeLiquidBlobColorSecondary: `${pre}.threeLiquidBlobBlobColorSecondary`,
    threeLiquidBlobCount: `${pre}.threeLiquidBlobBlobCount`,
    threeLiquidBlobMergeStrength: `${pre}.threeLiquidBlobMergeStrength`,
    threeLiquidBlobWobbleSpeed: `${pre}.threeLiquidBlobWobbleSpeed`,
    threeLiquidBlobBassDrive: `${pre}.threeLiquidBlobBassDrive`,
    threeLiquidBlobBloom: `${pre}.threeLiquidBlobBloomEnabled`,
    threeLiquidBlobBloomStrength: `${pre}.threeLiquidBlobBloomStrength`,
    threeLiquidBlobShape: `${pre}.threeLiquidBlobShapeConfig`,
    threeAuroraColorLow: `${pre}.threeAuroraRibbonColorLow`,
    threeAuroraColorHigh: `${pre}.threeAuroraRibbonColorHigh`,
    threeAuroraRibbonCount: `${pre}.threeAuroraRibbonRibbonCount`,
    threeAuroraRibbonWidth: `${pre}.threeAuroraRibbonRibbonWidth`,
    threeAuroraWaveAmplitude: `${pre}.threeAuroraRibbonWaveAmplitude`,
    threeAuroraWaveSpeed: `${pre}.threeAuroraRibbonWaveSpeed`,
    threeAuroraBassBandIndex: `${pre}.threeAuroraRibbonBassBandIndex`,
    threeAuroraBloom: `${pre}.threeAuroraRibbonBloomEnabled`,
    threeAuroraBloomStrength: `${pre}.threeAuroraRibbonBloomStrength`,
    threeAuroraAutoRotateSpeed: `${pre}.threeAuroraRibbonAutoRotateSpeedDeg`,
    threeAuroraShape: `${pre}.threeAuroraRibbonShapeConfig`,
    threeBreathingRingColor: `${pre}.threeBreathingRingsRingColor`,
    threeBreathingRingCount: `${pre}.threeBreathingRingsRingCount`,
    threeBreathingBaseRadius: `${pre}.threeBreathingRingsBaseRadius`,
    threeBreathingRadiusStep: `${pre}.threeBreathingRingsRadiusStep`,
    threeBreathingPulseStrength: `${pre}.threeBreathingRingsPulseStrength`,
    threeBreathingTubeRadius: `${pre}.threeBreathingRingsTubeRadius`,
    threeBreathingBloom: `${pre}.threeBreathingRingsBloomEnabled`,
    threeBreathingBloomStrength: `${pre}.threeBreathingRingsBloomStrength`,
    threeBreathingAutoRotateSpeed: `${pre}.threeBreathingRingsAutoRotateSpeedDeg`,
    threeBreathingShape: `${pre}.threeBreathingRingsShapeConfig`,
    threeNoiseColorLow: `${pre}.threeNoiseLandscapeColorLow`,
    threeNoiseColorHigh: `${pre}.threeNoiseLandscapeColorHigh`,
    threeNoiseGridSize: `${pre}.threeNoiseLandscapeGridSize`,
    threeNoiseHeightScale: `${pre}.threeNoiseLandscapeHeightScale`,
    threeNoiseNoiseScale: `${pre}.threeNoiseLandscapeNoiseScale`,
    threeNoiseScrollSpeed: `${pre}.threeNoiseLandscapeScrollSpeed`,
    threeNoiseWireframe: `${pre}.threeNoiseLandscapeWireframeOverlay`,
    threeNoiseBloom: `${pre}.threeNoiseLandscapeBloomEnabled`,
    threeNoiseBloomStrength: `${pre}.threeNoiseLandscapeBloomStrength`,
    threeNoiseCameraPitch: `${pre}.threeNoiseLandscapeCameraPitchDeg`,
    threeNoiseShape: `${pre}.threeNoiseLandscapeShapeConfig`,
    threeLavaLampColorWarm: `${pre}.threeLavaLampColorWarm`,
    threeLavaLampColorCool: `${pre}.threeLavaLampColorCool`,
    threeLavaLampBlobCount: `${pre}.threeLavaLampBlobCount`,
    threeLavaLampMergeStrength: `${pre}.threeLavaLampMergeStrength`,
    threeLavaLampBuoyancySpeed: `${pre}.threeLavaLampBuoyancySpeed`,
    threeLavaLampBassDrive: `${pre}.threeLavaLampBassDrive`,
    threeLavaLampBloom: `${pre}.threeLavaLampBloomEnabled`,
    threeLavaLampBloomStrength: `${pre}.threeLavaLampBloomStrength`,
    threeLavaLampShape: `${pre}.threeLavaLampShapeConfig`,
    threeOilMarbleColor1: `${pre}.threeOilMarbleColor1`,
    threeOilMarbleColor2: `${pre}.threeOilMarbleColor2`,
    threeOilMarbleColor3: `${pre}.threeOilMarbleColor3`,
    threeOilMarbleColor4: `${pre}.threeOilMarbleColor4`,
    threeOilMarbleColor4Enabled: `${pre}.threeOilMarbleColor4Enabled`,
    threeOilMarbleFlowSpeed: `${pre}.threeOilMarbleFlowSpeed`,
    threeOilMarbleNoiseScale: `${pre}.threeOilMarbleNoiseScale`,
    threeOilMarbleWarpStrength: `${pre}.threeOilMarbleWarpStrength`,
    threeOilMarbleReactiveness: `${pre}.threeOilMarbleReactiveness`,
    threeOilMarbleBloom: `${pre}.threeOilMarbleBloomEnabled`,
    threeOilMarbleBloomStrength: `${pre}.threeOilMarbleBloomStrength`,
    threeOilMarbleShape: `${pre}.threeOilMarbleShapeConfig`,
    threePearlChainColor1: `${pre}.threePearlChainColor1`,
    threePearlChainColor2: `${pre}.threePearlChainColor2`,
    threePearlChainColor3: `${pre}.threePearlChainColor3`,
    threePearlChainPearlCount: `${pre}.threePearlChainPearlCount`,
    threePearlChainChainRadius: `${pre}.threePearlChainChainRadius`,
    threePearlChainPearlSize: `${pre}.threePearlChainPearlSize`,
    threePearlChainSwaySpeed: `${pre}.threePearlChainSwaySpeed`,
    threePearlChainMergeStrength: `${pre}.threePearlChainMergeStrength`,
    threePearlChainBloom: `${pre}.threePearlChainBloomEnabled`,
    threePearlChainBloomStrength: `${pre}.threePearlChainBloomStrength`,
    threePearlChainShape: `${pre}.threePearlChainShapeConfig`,
    threeCrystalGemColorCore: `${pre}.threeCrystalGemColorCore`,
    threeCrystalGemColorEdge: `${pre}.threeCrystalGemColorEdge`,
    threeCrystalGemColorHighlight: `${pre}.threeCrystalGemColorHighlight`,
    threeCrystalGemGemCount: `${pre}.threeCrystalGemGemCount`,
    threeCrystalGemFacetSharpness: `${pre}.threeCrystalGemFacetSharpness`,
    threeCrystalGemRotationSpeedDeg: `${pre}.threeCrystalGemRotationSpeedDeg`,
    threeCrystalGemChromatic: `${pre}.threeCrystalGemChromaticEnabled`,
    threeCrystalGemChromaticOffset: `${pre}.threeCrystalGemChromaticOffset`,
    threeCrystalGemBloom: `${pre}.threeCrystalGemBloomEnabled`,
    threeCrystalGemBloomStrength: `${pre}.threeCrystalGemBloomStrength`,
    threeCrystalGemShape: `${pre}.threeCrystalGemShapeConfig`,
    mainBgColor: `${pre}.mainBgColor`,
    mainBgAlpha: `${pre}.mainBgAlpha`,
    overlayBlur: `${pre}.overlayBlurEnabled`,
  };
}

/**
 * 读取某窗专属配置；若无则回退旧全局 {@link STORAGE_KEYS}（升级迁移）。
 * @param {Storage} ls
 * @param {string} windowLabel
 * @param {keyof typeof STORAGE_KEYS} prop
 */
export function readWindowStorageString(ls, windowLabel, prop) {
  const wk = windowStorageKeys(windowLabel);
  const primary = ls.getItem(wk[prop]);
  if (primary != null && primary !== "") {
    return primary;
  }
  return ls.getItem(STORAGE_KEYS[prop]);
}

/**
 * @param {Storage} ls
 * @param {string} windowLabel
 * @param {keyof typeof STORAGE_KEYS} prop
 * @param {string} value
 */
export function writeWindowStorageString(ls, windowLabel, prop, value) {
  const wk = windowStorageKeys(windowLabel);
  ls.setItem(wk[prop], value);
}
